var basicVert = {"code":"\n#line 1 1 \n  uniform mat4 _uni_projMat;\r \n#line 2 1 \n  uniform mat4 _uni_viewMat;\r \n#line 3 1 \n  \r \n#line 4 1 \n  uniform mat4 _uni_modelMat;\r \n#line 5 1 \n  \r \n#line 6 1 \n  \r \n#line 7 1 \n  attribute vec3 aVertex;\r \n#line 8 1 \n  \r \n#line 9 1 \n  \r \n#line 10 1 \n  attribute vec2 aUV;\r \n#line 11 1 \n  \r \n#line 12 1 \n  varying vec2 vUV;\r \n#line 13 1 \n  \r \n#line 14 1 \n  void main(void) {\r \n#line 15 1 \n  \r \n#line 16 1 \n      vec3 position = aVertex;\r \n#line 17 1 \n  \r \n#line 18 1 \n      gl_Position = _uni_projMat * _uni_viewMat * _uni_modelMat * vec4(position, 1.0);\r \n#line 19 1 \n      vUV = aUV;\r \n#line 20 1 \n  }\r \n#line 21 1 \n   \n","extension":{},"attribute":{"aVertex":{"type":"vec3","value":{"size":"3","stride":"20","offset":"0"},"name":"quadBuffer"},"aUV":{"type":"vec2","value":{"size":"2","stride":"20","offset":"12"},"name":"quadBuffer"}},"uniform":{"_uni_projMat":{"type":"mat4","value":null},"_uni_viewMat":{"type":"mat4","value":null},"_uni_modelMat":{"type":"mat4","value":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}},"file":{"1":"./shaders\\glsl\\basic-vert.glsl"}};

var basicFrag = {"code":"\n#line 1 1 \n  precision highp float;\r \n#line 2 1 \n  \r \n#line 3 1 \n  \r \n#line 4 1 \n  uniform vec3 uColor;\r \n#line 5 1 \n  \r \n#line 6 1 \n  varying vec2 vUV;\r \n#line 7 1 \n  \r \n#line 8 1 \n  uniform sampler2D uTex;\r \n#line 9 1 \n  \r \n#line 10 1 \n  void main(void) {\r \n#line 11 1 \n  \r \n#line 12 1 \n     gl_FragColor =   // vec4(uColor, 1.0);\r \n#line 13 1 \n          vec4(texture2D(uTex,vUV).rgb, 1.0);\r \n#line 14 1 \n  }\r \n#line 15 1 \n   \n","extension":{},"attribute":{},"uniform":{"uColor":{"type":"vec3","value":[0,1,0]},"uTex":{"type":"sampler2D","value":0}},"file":{"1":"./shaders\\glsl\\basic-frag.glsl"}};

var vaoQuadVert = {"code":"\n#line 1 1 \n  #version 300 es\r \n#line 2 1 \n  #define POSITION_LOCATION 0\r \n#line 3 1 \n  #define COLOR_LOCATION 1\r \n#line 4 1 \n  \r \n#line 5 1 \n  precision highp float;\r \n#line 6 1 \n  precision highp int;\r \n#line 7 1 \n  \r \n#line 8 1 \n  \r \n#line 9 1 \n  layout(location = POSITION_LOCATION) in vec2 pos;\r \n#line 10 1 \n  \r \n#line 11 1 \n  \r \n#line 12 1 \n  layout(location = COLOR_LOCATION) in vec4 color;\r \n#line 13 1 \n  \r \n#line 14 1 \n  flat out vec4 v_color;\r \n#line 15 1 \n  \r \n#line 16 1 \n  void main()\r \n#line 17 1 \n  {\r \n#line 18 1 \n      v_color = color;\r \n#line 19 1 \n      gl_Position = vec4(pos, 0.0, 1.0);\r \n#line 20 1 \n  } \n","extension":{},"attribute":{},"uniform":{},"file":{"1":"./shaders\\glsl\\vaoQuad-vert.glsl"}};

var vaoQuadFrag = {"code":"\n#line 1 1 \n  #version 300 es\r \n#line 2 1 \n  precision highp float;\r \n#line 3 1 \n  precision highp int;\r \n#line 4 1 \n  \r \n#line 5 1 \n  flat in vec4 v_color;\r \n#line 6 1 \n  out vec4 color;\r \n#line 7 1 \n  \r \n#line 8 1 \n  void main()\r \n#line 9 1 \n  {\r \n#line 10 1 \n      color = v_color;\r \n#line 11 1 \n  } \n","extension":{},"attribute":{},"uniform":{},"file":{"1":"./shaders\\glsl\\vaoQuad-frag.glsl"}};

export { basicFrag, basicVert, vaoQuadFrag, vaoQuadVert };
